- package-lock.json
- src/schema/schema.graphql
- src/schema/schema.ts
- add facility to pass offset and limit to graphql query for calendar
> PREAPPS-518

- package-lock.json
- package.json
- src/normalize/index.ts
Required for the checkout preview script to work properly.
> Hotfix: Typescript Upgrade

- package-lock.json
- package.json
- src/batch-client/index.ts
- src/normalize/entities.ts
- src/normalize/index.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- src/schema/schema.ts
> PREAPPS-613: Implement Add/modify/delete Signature

- package-lock.json
- src/apollo/local-batch-link.ts
- src/apollo/zimbra-error-link.ts
- src/batch-client/index.ts
- src/batch-client/types.ts
- src/request/index.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- src/schema/schema.ts
- Add login, logout and change password apis in graphql
- Make sure event emitter passes data to subscribers from BatchLink
- Fix issue where request object was trying to json parse request which had http status 502 and no data, which was passing javascript error in graphql error instead of actual error
> PREAPPS-629

- src/apollo/zimbra-error-link.ts
- src/schema/generated-schema-types.ts
- Add function to unregister all handlers
> PREAPPS-573

- src/normalize/entities.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
**NOTE** breaking change, switching `rt` to `replyType`
> PREAPPS-811: grab rt from message response

- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
This adds zimlets to AccountInfo in order to get the names of enabled/disabled Zimlets.
> PREAPPS-121: Use server resource consolidation to get Zimlets

- package-lock.json
- src/apollo/zimbra-in-memory-cache.ts
- src/batch-client/index.ts
- src/batch-client/types.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- src/schema/schema.ts
> PREAPPS-856:: User should able to fetch public certificate of the recipient from Contact, GAL or LDAP. (WIP)

- src/batch-client/index.ts
- src/batch-client/types.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
Also pass on response of `AuthRequest` instead of resolving with boolean.
> PREAPPS-1038: Add `tokenType` option to `AuthRequest`

- package-lock.json
- src/apollo/offline-queue-link/errors.ts
- src/apollo/offline-queue-link/index.ts
- src/apollo/offline-queue-link/types.ts
- src/apollo/offline-queue-link/util.ts
- src/apollo/sync-offline-operations/index.ts
- src/apollo/sync-offline-operations/types.ts
- src/apollo/types.ts
Return a Promise from the `retry` method resolving after the queue is processed. This allows a consumer to respond to the sync operation beginning/ending.
> PREAPPS-825: Automatic send receive of emails

- src/batch-client/index.ts
- src/batch-client/types.ts
- src/normalize/entities.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- src/schema/schema.ts
This PR adds a Query and 2 Mutations in order to replace direct API calls with GraphQL calls on the client.
> Reminders Queries

- src/batch-client/index.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
Reverts Zimbra/zm-api-js-client#84
> Revert "Return the ID of a created appointment from createAppointment"

- package-lock.json
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- Added a field to save Contact source folder id
> PREAPPS-1125: Contact Chooser not showing all contact folders

- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
Add `zimbraPrefWebClientOfflineBrowserKey` to preferences input.
> PREAPPS-1447: Add 'Offline Mode' to the Settings

- package-lock.json
- package.json
- latest version has a fix for memory leak (https://github.com/apollographql/apollo-client/pull/4251) so try to see if that helps
> memory-leaks Upgrade apollo-cache-inmemory

- src/schema/schema.graphql
Added a mutation to schema for saving local folder emails
> PREAPPS-1474: Discover existing Zimbra X Local Email folder

- src/schema/schema.graphql
correcting eslint issue for zm-x-web repo
> PREAPPS-1701: Update attachment metadata after mounting archive folder

- package-lock.json
- package.json
- rollup.config.js
- src/batch-client/index.ts
- src/normalize/entities.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- src/schema/schema.ts
This upgrades our GraphQL stack to `14` and some related types.
> PREAPPS-1316: Upgrade to Webpack 4 

- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- Added schema attribute for polling interval input
> PREAPPS-355: Add a preference pane that lets you configure how often the app polls for new mail

- package-lock.json
- src/utils/normalize-mime-parts.ts
ics files are filtered out while normalizing mime parts.
> PREAPPS-1058: Respond to invite from Calendar

- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- Added required account pref attrs for reading/writing `zimbraPrefMailRequestReadReceipts`
> PREAPPS-1885: Read Receipts | Requesting for Read Receipts

- package-lock.json
- src/normalize/entities.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
Added recurring rules for monthly and yearly.
> PREAPPS-2079: Monthly, Yearly | Custom recurrence for events

- src/batch-client/index.ts
PREAPPS-2305 Orange 5.0 | local folder message doesn't appears, Getting console error while moving message to local folder
- Fix typo where id was passed as content
> PREAPPS-2306 Orange 5.0 | not able to View S/MIME mails

- package-lock.json
- src/batch-client/index.ts
- src/normalize/entities.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- src/schema/schema.ts
Forward invite message as an event instead of as a message
> PREAPPS-1055: Forward invite message as an event instead of as a message

- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
…liveryDisabled are added in account query input and type
> PREAPPS-630: Default account: 'Forward mail' setting feature is not getting saved

- package-lock.json
- package.json
- src/batch-client/index.ts
- src/batch-client/types.ts
- src/request/index.ts
- src/request/types.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- src/schema/schema.ts
- Add CSRF implementation in api client
- this implementation is independent from application code, so if application code wants csrf support then it can enable it at login time
- even if application doesn't enable csrf support, everything should work with less security
> PREAPPS-2678 Implementation of CSRF support

- src/schema/schema.graphql
Add `zimbraFeatureViewInHtmlEnabled` setting.
> PREAPPS-2908: Reintroduce NE HF Doc Preview for all file types

- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
Add `action` property to ShareInputAction.
> PREAPPS-2088: Email notifications on changing the share rights

- src/schema/notifications.ts
- types.ts
Added 'untag' action in ActionOps enum
> PREAPPS-2754: Tags | Tag emails with custom tags

- package-lock.json
- package.json
- src/schema/notifications.ts
- Merge to master and will publish to NPM after that
> Merge to master for release/1.0.1

- src/batch-client/index.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- src/schema/schema.ts
Add `modifyProps` batch client method and mutations.
> ZX-1073 Create a means to add your Skype name to the settings

- src/normalize/entities.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
Add `otherAtt` field to CalendarItemHitInfo.
> PREAPPS-3082: Reply/Reply All to all participants of a meeting from calendar view of a meeting

- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
Added zimbraPrefClientType attribute into the preferences and preferencesInput.
> PREAPPS-3706: Provide an option to switch to Legacy UI from Zimbra X UI

- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
-Replaced zimbrax with modern.
> PREAPPS-4182: Change login options available to the user

- src/batch-client/index.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
Event invitation sent to email alias and marked Accept or Tentative - response cannot be changed later in calendar. Also, popup & event detail are missing Response dropdown & event detail are missing Response dropdown
> PREAPPS-4560: Event invitation sent to email alias and marked Accept or Tentative - response cannot be changed later in calendar

- src/schema/schema.graphql
Changes:
1. changePasswordURL added to AccountInfo type.
> PREAPPS-4491: Allow client-config override of Change Password action

- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- added an attribute to retrive the tag enabled config for user
> PREAPPS-4667: Disable Tagging based on admin settings

- src/schema/schema.graphql
Changes:
1. CalendarsAndAppointment query related changes removed.
> PREAPPS-4212: Move 'New Event' from message functionality to core product

- src/request/index.ts
- added a fix to handle the gateway timeout and bad gateway errors properly
> PREAPPS-4720: Handle getway timeout/bad gateway errors properly in the app

- src/batch-client/index.ts
- src/batch-client/types.ts
- src/normalize/entities.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- src/schema/schema.ts
May need to update SaveDraftRequest
> PREAPPS-4810 : Briefcase | Upload and download files

- src/schema/notifications.ts
Added additional required fields in getNewMail query
> PREAPPS-4696: New mail notifications to have more information

- src/batch-client/index.ts
- src/schema/schema.graphql
- src/schema/schema.ts
- change save-draft and send-message mutations so that they accept account name
> PREAPPS-5005 Modern UI Issue: Problem with "send as" delegate rights and "Save a copy of sent messages to my Sent folder"

- src/batch-client/types.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- types.ts
To implement dumpster feature added zimbraDumpsterEnabled and 'recover' in ActionOps
> PREAPPS-3826 Implement Dumpster

- src/batch-client/index.ts
- src/request/types.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- src/schema/schema.ts
There are one query and three mutations requires to be added.
API - GetDeviceStatusRequest
API - SuspendDeviceRequest
API - ResumeDeviceRequest
API - RemoveDeviceRequest
These will enable us to retrieve necessary data and update the same.
> PREAPPS-4846 : Adding Device status related graphql queries.

- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
-Added password field into the ExternalAccountModifyAttrsInput and remove emailAddress as it was causing issues.
-Added attributes in ExternalAccountModifyAttrsInput.
> PREAPPS-4972: Updated fields into the ExternalAccountModifyAttrsInput as per required 

- src/batch-client/index.ts
- src/batch-client/notifier/index.ts
- src/batch-client/types.ts
- src/request/index.ts
- src/request/types.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- src/schema/schema.ts
- updated noop code to include parameters
> PREAPPS-4971: Fix reminders refetch only when notifications for appt present

- src/batch-client/types.ts
- src/schema/schema.graphql
Added recursive property to action request
> PREAPPS-5241: "Empty folder" option

- src/batch-client/index.ts
- src/batch-client/types.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
dryRun attribute added to changePassword API and PasswordBlockCommonEnabled key added to getInfo schema
> PREAPPS-5171: Password Conformance guidance in Modern UI Part 2

- src/batch-client/index.ts
- src/batch-client/types.ts
- src/schema/schema.graphql
Added dryRun flag in resetPassword request
> PREAPPS-5244: Modern UI - Reset Password flow: handle remote rules

- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- add zimbraBrandingFolderName into account info response
> PREAPPS-5580 Branding | add support for admin defined branding

- package-lock.json
- package.json
- src/batch-client/types.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
electron-move-db-to-main: added generated schema file
electron-move-db-to-main: fixed uglifyjs error for windows build
> PREAPPS-5653: move db operations to main process

- src/batch-client/types.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- src/schema/schema.ts
> PREAPPS-5613: Add a separation in online and local folders

- src/batch-client/index.ts
- src/batch-client/types.ts
- src/schema/schema.graphql
Modified Reset Password request to support password rules
> PREAPPS-5772: Support 2FA and forgot password at the same time. | Modern UI

- src/batch-client/index.ts
- src/normalize/entities.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- src/schema/schema.ts
We are going to allow user to choose contacts from HAB with new contact-chooser dialog.
HAB related API calls needs to be added for ModernUI.
GetHABRequest API is implmented.
> PREAPPS-5867 : Adding HAB APIs.

- src/batch-client/index.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- src/schema/schema.ts
-Added user APIs required for user device management.
-Updated resumeDevice with allowDevice & suspendDevice with QuarantineDevice requests
> ZCS-10284: Modern UI Zimlet for Users for Device Management

- README.md
- package-lock.json
- package.json
- rollup.config.js
- src/batch-client/index.ts
- src/batch-client/types.ts
- src/request/index.ts
- src/request/types.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- src/schema/schema.ts
PREAPPS-5653: added generated schema file
PREAPPS-5653 fixed uglifyjs error for windows build
PREAPPS-5653: added base64 input in the mimepart
> ZAPPD-45: Desktop App Sync feature

- src/batch-client/index.ts
- src/normalize/entities.ts
- src/request/types.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- src/schema/schema.ts
Certificate management related graphql integrations.
> PREAPPS-6192 Adding certificate CRUD operations.

- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- src/utils/normalize-email-addresses.ts
Adding `replyTo` to `MessageInfo`.
**Related PR:**
* https://github.com/ZimbraOS/zm-x-web/pull/3635
> ZBUG-2318: added replyTo to MessageInfo

- src/batch-client/index.ts
- src/normalize/entities.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
Receiver will be able to read signed/encrypted message.
Server does the decryption and provide decrypted content in case of server-smime.
Display info that the message was Signed/Encrypted while viewing email.
Display info if server responded with exception.
> PREAPPS-6193 : Display signed/encrypted message properly.

- src/utils/normalize-mime-parts.ts
made changes in normalize-mime-parts
> ZBUG-2248 Attachment (.p7m) present in an email NOT visible from Webmail Modern UI - made changes in normalize-mime-parts

- src/apollo/zimbra-in-memory-cache.ts
- src/batch-client/index.ts
-Made changes in Zimbra-in-memory-cache.ts for creating unique id for caching.
-Made changes in batch-client/index.ts
In updateAbsoluteFolderPath
> ZBUG-1922 Shared folder Navigation issue in ModernUI

- src/batch-client/index.ts
- src/batch-client/types.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- src/schema/schema.ts
- Requesting payload with `sendAsDistList` and `sendOnBehalfOfDistList` right on `DiscoverRights` request.
> ZBUG-1926: No option to select persona in the From field in modern UI

- src/batch-client/index.ts
- src/normalize/entities.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
-Added truncated property in mime parts
> ZBUG-2363 Modern UI, message body displaying partially

- src/batch-client/index.ts
- Normalize other attribute of contact on SearchGal response
> ZBUG-2612: Modern UI, Unable to search contact in GAL through alias name

- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
-added zimbraFeatureAntispamEnabled property  in graphql schema
> PREAPPS-6617 Hide all spam related options when the spam feature is disabled

- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
-added the zimbraFeatureTasksEnabled to the schema of account info
> PREAPPS-6616:Hide task list from calendar when the task feature is disabled

- src/batch-client/index.ts
Sending CreateSignatureRequest in Batch as like classic UI is doing.
> PREAPPS-6777: Intermittent failures in saving standard/reply or imap signatures and using signatures while composing

- src/normalize/entities.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- Adding doc input in Save document request for Making older version as current
> PREAPPS-6793: "Make current version" option for the file

- src/normalize/entities.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- Adding doc input in Save document request for Making older version as current
> PREAPPS-6793: "Make current version" option for the file.

- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- src/schema/schema.ts
- Update createCalendar mutation and schema to support parentFolderId field
> PREAPPS-5105: add parent folder ID to calendar schema

- src/schema/schema.graphql
Modify content to accept an array.
> PREAPPS-7028: Implement plain text Signature in Modern UI

- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
-Add zimbraHelpModernURL attribute.
> PREAPPS-7121:Modern: Help screen display function

- src/batch-client/index.ts
Fixed modification of folder absolute path.
> ZBUG-2793 Modern UI: Emails in shared subfolders are not displaying.

- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
Implement Save-Search for Contacts, Calendar events and Briefcase files
- Added types field for folders, which will be used to seggregate search folders
> PREAPPS-6726: Implement Save-Search for Contacts, Calendar events and Briefcase files

- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
considering zimbraFeatureExportFolderEnabled and zimbraFeatureImportFolderEnabled attributes
> PREAPPS-7222 Disable import/export option based on zimbra feature attribute

- src/normalize/entities.ts
Mapped searchFolder to Folder object
> PREAPPS-7213: Add context menu on right click of saved searches folder for Calender

- src/normalize/entities.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
Related PR and issue description - https://github.com/ZimbraOS/zm-x-web/pull/4531
> ZBUG-3422: Added timezoneOffset property to event instance type

- src/batch-client/index.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- Get list of all the distribution list members.
> PREAPPS-4851: Expand a distribution list

- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- zimbraPrefExternalSendersType LDAP attribute added into the schema.
> PREAPPS-7481: No "send custom message to those not in my organization and address book" option in OOO

- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- Added two new parameters for loading the DL members on scroll event
> PREAPPS-7500: Load DL members on the scroll event.

- src/schema/schema.ts
Fix regression caused by https://github.com/Zimbra/zm-api-js-client/pull/608/files#diff-2f62190d7ad815da92e5dcf270fdd6e290f3362cf453d2951e2f4d7ed46e2badR397
by adding the missing change.
> PREAPPS-7539: Fix Desktop Test Failures Introduced Via PREAPPS-7425

- src/batch-client/index.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- src/schema/schema.ts
- Added new query to fetched distribution lists details
> PREAPPS-7532: Distribution list is missing on choose contact popup

- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- Added zimraFeatureMailRecallEnabled and zimbraFeatureMailRecallTime LDAP attributes
> PREAPPS-7326:  Disable Mail recall option if mail recall time is elapsed

- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- InviteCondition schema changes
> PREAPPS-7452: Some filter conditions are not supported on Modern UI

- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
InviteCondition schema changes
> PREAPPS-7454: Some filter conditions are not supported on Modern UI 

- src/batch-client/index.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- src/schema/schema.ts
- Added query for 'GetDistributionList'
- Added mutation for 'SubscribeDistributionList'
> PREAPPS-7446: As the admin of a distribution list I want to be able to view DL properties in Modern UI

- src/normalize/entities.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
-  Updated schema to add or remove DL members
PR for [zm-x-web](https://github.com/ZimbraOS/zm-x-web/pull/4860)
> PREAPPS-7663: As the admin of a distribution list add ability to Add/delete Distribution List members in Modern UI

- src/normalize/entities.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
PREAPPS-7684: Updated the DLActionInput schema for subscription-related operations and added a dlsubs object to retrieve subscription-related information.
> PREAPPS-7684: No option available for accept/reject the request

- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- Added zimbraClassicWebClientDisabled attribute, Get value of it from ClientInfoResponse.
> ZCS-14933 Prevent access of classic ui when zimbraClassicWebClientDisabled is TRUE

- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
Added `zimbraFeatureSharedFolderMobileSyncEnabled` in **AccountInfoAttrs** 
Added `activeSyncDisabled` in **shareInfo**
> PREAPPS-7771: Shared folder synchronization to mobile.

- src/batch-client/index.ts
- src/batch-client/types.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- Added support of excludeUid on freebusy api.
> ZBUG-3997 Meeting Invitation Mail Shows Conflict Banner Even When No Conflict

- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
Added zimbraPrefDeleteInviteOnReply into PreferencesInput
> PREAPPS-7883: Implement option to turn off deletion of appointments email after responding to sender for Modern Ui Zimbra10

- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
- Added attribute zimbraSkinLogoLoginBanner and zimbraSkinLogoAppBanner in ClientInfoAttributes attributes
> PREAPPS-7809: Update Logo component to support image added to ldap attributes

- src/normalize/entities.ts
- src/schema/schema.graphql
Updated CalendarItemReply type object.
> PREAPPS-7911: Getting error when viewing already accepted/rejected email invite

- src/batch-client/index.ts
- src/batch-client/types.ts
- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
Updating parameters for ChangePasswordRequest/Response.
> PREAPPS-7988: updated parameters for ChangePassword

- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
Disable Mail recall option if mail recall time is elapsed
- Added zimraFeatureMailRecallEnabled and zimbraFeatureMailRecallTime LDAP attributes
> PREAPPS-7601:  Modern UI mail recall end to end functionality

- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
Added the `zimbraDataSourceMaxNumEntries` LDAP attribute for fetching the data source limit.
> ZBUG-4602: L10N: need to translate error message on adding more than 20 Accounts in Settings

- src/utils/normalize-mime-parts.ts
Root cause -
Improper assignment of text content to html content - https://github.com/Zimbra/zm-api-js-client/compare/master...ZBUG-4672?expand=1#diff-e45d10e0537bee3ad5981db1ce10e21347c0c9de7e8a4671db46c65799e1eb3eL166
when a multipart email (with inline image) is sent from IOS email client, then zm-api-js client library converts the text to html since it contains inline image and needs to be displayed as html in email preview (emails sent from ios email client does not contain any html parts). There is some technical issue in the conversion logic because of which the some content from email is not getting displayed.
Solution -
html content should be evaluated after all the parts are iterated so that we can get entire text content along with attachment. Stored these contents in a …
> ZBUG-4672: Fixed content missing in email with inline images sent from ios client

- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
Added provision to batch contactAction request
> PREAPPS-8510: Contact item in list should show tagging information

- src/schema/generated-schema-types.ts
- src/schema/schema.graphql
Adding attributes for pop and imap feature and preferences.
> PREAPPS-8631: added pop/imap feature and pref attributes
