src/request/index.ts

so safari 10 doesn't explode when the `headers` param is `undefined`

PREAPPS-341 add fallback for request headers option 

---

package.json

Keep the `_createClass` name to avoid it being removed by dead code elimination.
Keep function names because `graphql` relies on them.

Adjust settings to `uglifyjs` mangler to allow CJS and UMD bundles to build correctly.

---

package-lock.json
src/batch-client/index.ts
src/normalize/entities.ts
src/schema/generated-schema-types.ts
src/schema/schema.graphql
src/schema/schema.ts

This should not be published until https://github.com/Zimbra/zm-x-web/pull/35 is merged, which stops using these in favor of the standard `getFolder` query

PREAPPS-548 Remove unused and shouldn't be used calendars and folders queries

---

src/normalize/entities.ts
src/schema/notifications.ts
src/schema/schema.graphql

`permissions` is added into Folder schema and it's value will be available in case of linked folder only.

PREAPPS-555 Choose calendar to add event to

---

src/batch-client/types.ts

File(zm-x-web-private): src/components/mail-pane/index.js
Whenever any action is selected from context menu that is opened by right clicking on mail item, an error was getting thrown.
This was because we're trying to retrieve data to update the cache in the mutation of the respective action, and that data had "MessageInfo" as key instead of "Message". But we were using "ActionResultType" object as selector on that data.

PREAPPS:634:: A dependancy related to PREAPPS-371

---

src/batch-client/index.ts

This is breaking moving mail messages between folders on `master`.
There are some consumers that use the raw `action` method, so we always need to be calling `denormalize` on the arguments passed it.

Hotfix: Always denormalize arguments passed to `action`

---

package-lock.json
package.json
src/batch-client/index.ts
src/normalize/index.ts
src/request/index.ts
src/schema/notifications.ts
src/schema/schema.ts
src/utils/map-values-deep.ts

Build was failing because of this error
```
> @zimbra/api-client@5.0.0 rollup:cjs /home/circleci/repo/node_modules/@zimbra/api-client
> cross-var rollup -c rollup.config.js -m -f cjs -n $npm_package_amdName $npm_package_source -o $npm_package_main
index.ts → dist/zm-api-js-client.js...
[!] Error: 'mapValues' is not exported by node_modules/lodash/lodash.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
src/schema/schema.ts (2:9)
1: import { makeExecutableSchema } from 'graphql-tools';
2: import { mapValues } from 'lodash';
^
3: 
4: import {
```

Fix issue with api-client build

---

src/apollo/zimbra-in-memory-cache.ts

It turns out that an `AutoCompleteMatch` is not guarenteed to have an `id`. This changes the dataId for `AutoCompleteMatch` to be unique based on the email address found in the match.

PREAPPS-1148: Autocomplete results contain repeats

---

package-lock.json
src/batch-client/index.ts
src/schema/generated-schema-types.ts
src/schema/schema.graphql

Companion PR of [zm-x-web's #449](https://github.com/ZimbraOS/zm-x-web/pull/449).
This is needed because for Jitsi/OnlyOffice integrations, we require the `inviteId` generated upon creation of an appointment, in order to update that appointment on the spot.

Return the ID of a created appointment from createAppointment

---

src/apollo/sync-offline-operations/index.ts

- Fixed error where empty graphql cache was throwing javascript error

PREAPPS-1160 Use indexdb for storing graphql cache

---

package-lock.json
package.json

- event-stream module has security flaw and module was removed from npm to protect users
- npm-run-all module was using this module so when npm install tried to fetch and install event-stream module from npm, module was not present and netlify deploys were failing
- fixed issue by upgrading version of npm-run-all which removed dependency on event-stream module
https://github.com/mysticatea/npm-run-all/commit/57d72eb98c2ce108f07d2a2cf1b44d57f08ec3ca#commitcomment-31468478

fix_package_lock Upgrade npm-run-all module to fix security flaw and fix netlify deploy failing issue

---

src/normalize/entities.ts
src/schema/generated-schema-types.ts
src/schema/schema.graphql

Added field "tzo" which was exist in SOAP response but wasn't in 'CalendarItemHitInfo' schema.

PREAPPS-625: Single day All Day appointments show over 2 days

---

package.json

Only the `moderate` flag is required to catch `moderate`, `high`, and `critical` vulnerabilities.

Simplify `audit-ci` expression

---

src/schema/schema.graphql

- change type of zimbraPrefDefaultCalendarId to ID instead of Int

PREAPPS-1990 Calendar | Cannot save "Default Calendar" setting due to GraphQL error

---

src/apollo/offline-queue-link/index.ts

Expose the `SyncOfflineOperations` class from `OfflineQueueLink`.

PREAPPS-2128: On network reconnection, Outbox message is received twice, draft message shows twice in Trash; same changes synced twice to server

---

src/schema/generated-schema-types.ts
src/schema/schema.graphql

Add `zimbraFeatureResetPasswordStatus` to AccountInfoAttrs.

PREAPPS-2296: Account Recovery shows misleading error when password reset is disabled

---

src/schema/generated-schema-types.ts
src/schema/schema.graphql

Move `zimbraPrefSaveToSent` from `attrs` to `prefs`.
It seems like this was put in the wrong location a long time ago.

PREAPPS-2736: Do not save mail to sent folder

---

src/schema/notifications.ts
src/schema/schema.graphql

New mail(only with flag 'unread') received in notifications object is written to local cache using `@client` directive. Client query listening to the same is updated with new mail.

PREAPPS-1860: Show notifications when new messages arrive

---

src/batch-client/index.ts

- added a case to handle the updation of absFolderPath for shared items, when the entire mailbox is received as a shared item

PREAPPS-4393: Show shared mailbox with a user under Shared Folders

---

src/utils/normalize-mime-parts.ts

Remove special case for ICS attachments.

PREAPPS-4602: GraphQL error 'upload not found' shows after attaching .ics file; draft mail in Drafts does not contain .ics file

---

src/schema/generated-schema-types.ts
src/schema/schema.graphql

- this attribute is not being in use in the app
- also this attribute was mapped to integer but server uses gentime data format for this and both are not compatible as server was returning 20200721163834.298Z as value

PREAPPS-5175 Removed zimbraPasswordModifiedTime from graphql schema

---

src/utils/normalize-otherAttribute-contact.ts

the reason we need to cast userCertificate value to string:-
1) User Certificate comes as **string** when their is only one certificate available :-
2) User certificate comes as **Array** when their are multiple certificates:-

PREAPPS-4517:- TypeError when opening Synacor Global Address List

---

src/batch-client/constants.ts
src/batch-client/index.ts
src/batch-client/types.ts
src/schema/generated-schema-types.ts
src/schema/schema.graphql

Function setUnreadDescendentFlag will check only if the folder View is null or Message , null because the follders that are through imap or pop
hasUnreadDescendent will set the flag unreadDescendent if a folders subfolder or itself has a unread count

PREAPPS-5503: adding the unreadDescendent to check if any subfolder or the folder itself has a unread mails in the hireracy

---

src/utils/normalize-mime-parts.ts

Set the contentDisposition in the attachment item as per their classification while normalizing mime parts.

PREAPPS-6138: Handle attachments when ci / cd keys are not present in MIME

---

src/schema/generated-schema-types.ts
src/schema/schema.graphql
src/utils/normalize-otherAttribute-contact.ts

**Change:**
* added `phoneticLastName` and `phoneticFirstName` of a contact to graphql schema. Then they are stored in `attributes` rather than `attributes.other` of a contact data.
**Related PR:**
* https://github.com/ZimbraOS/zm-x-web/pull/3470

ZBUG-1720: added phoneticFirst/LastName to graphql schema

---

.circleci/config.yml
src/utils/normalize-mime-parts.ts

Below Issues fixed
**Issue**: If attached EML file contains attachments then message view is showing those attachment as well. 
_Expected_- Message preview should show EML file only it should not display attachment of EML.
**Issue**: build job failing due to issue with lts version of circleci image.

PREAPPS-6472: Show EML attachment in the attachment section.

---

src/normalize/entities.ts
src/schema/generated-schema-types.ts
src/schema/schema.graphql
src/utils/normalize-otherAttribute-contact.ts

Problem:
- There is no way for user to add/remove public certificate in case of server-smime.
Solution:
- User can add public certificate into contact.
- User can remove public certificate from contact.
- This facilities will be available via secure-mail zimlet.
- Introduced a zimlet-slot 'contact-add-server-smime-cert'.
- Using 'userCertificate' attribute of contact to set aid of uploaded certificate into contact.

PREAPPS-6380 : Add-Remove certificate facility in contact.

---

src/utils/normalize-otherAttribute-contact.ts

Referring legacy client for List of contact attributes to be ignore
Legacy behaviour
Attributes to be ignore as per legacy
https://github.com/Zimbra/zm-web-client/blob/a95d3e1256cf5a7c0a04a6b8d02267c58e41d322/WebRoot/js/zimbraMail/abook/model/ZmContact.js#L335
Mentioned all list of attributes to be ignore in [PREAPPS-2893](https://jira.corp.synacor.com/browse/PREAPPS-2893)

ZBUG-2048: Weird fields are showing under contact in Modern UI

---

src/utils/normalize-mime-parts.ts

Modern UI shows inessential attachment with Unnamed on Read-receipt response message, Folder Share message and Undelivered message response.
Ignoring the message part to be consider as attachment based on content type

ZBUG-2332: Read recipient response as an attachment

---

src/batch-client/index.ts
src/normalize/entities.ts
src/request/types.ts
src/schema/generated-schema-types.ts
src/schema/schema.graphql
src/schema/schema.ts
src/utils/normalize-otherAttribute-contact.ts

Creates SendSecureMsgRequest related graphql schema.
Adding facility to give necessary parameters like 'sign' and 'encrypt' with SendSecureMsgRequest.
'sign' will be included while user wants to just sign any particular mail.
'sign' and 'encrypt' both will be included while user wants to sign+encrypt any particular mail.

PREAPPS-6191 : Sign/Sign+Encrypt emails using Server SMIME.

---

src/batch-client/index.ts
src/schema/generated-schema-types.ts
src/schema/schema.graphql

- Created sendBeacon request to terminate session. This request will be called from zm-x-web directly when 'beforeunload' event trigger. See this https://github.com/ZimbraOS/zm-x-web/pull/3829/files#diff-e422e4a89b3245e4203985dfafed63e4e7a9abcb7bfc93c6ed161e75d36aeb9bR5

ZBUG-2426: SAML SP-initiated logout does not work - zimbraWebClientLogoutURL

---

package-lock.json
package.json
src/apollo/local-batch-link.ts
src/apollo/offline-queue-link/index.ts
src/apollo/offline-queue-link/types.ts
src/apollo/offline-queue-link/util.ts
src/apollo/zimbra-in-memory-cache.ts
src/schema/session-handler.ts

- As per https://github.com/apollographql/apollo-client/issues/7005, if we use @apollo/client imports then it includes react related packages as well, but that gives problem for us as this package is used inside sync module also which is executed inside node environment and hence doesn't have react library present

PREAPPS-6581 Import from @apollo/client/core instead of @apollo/client

---

src/batch-client/index.ts
src/schema/generated-schema-types.ts
src/schema/schema.graphql

-Added zimbraPasswordAllowUsername to the schema of AccountInfoAttrs

PREAPPS-6698:Modern UI - Users should not be allowed to use username in the password

---

src/schema/generated-schema-types.ts
src/schema/schema.graphql

We need to check whether user is logged in through delegated admin access or not. Hence adding the relevant attribute in the schema.

PREAPPS-7160 add adminDelegated attribute in AccountInfo schema

---

src/schema/generated-schema-types.ts
src/schema/schema.graphql
src/utils/normalize-mime-parts.ts

- `src/utils/normalize-mime-parts.ts` lines 113 to 144: Fix for the issue - In Classic UI, create a draft message containing a signature with an inline image. Open the same draft in Modern UI, the signature image is displayed as an external attachment.

PREAPPS-7368: Implement Support Inline images in Signatures

---

src/schema/generated-schema-types.ts
src/schema/schema.graphql

- Added zimbraFeatureDistributionListFolderEnabled attribute in AccountInfoAttrs

PREAPPS-7554: Distribution list is missing in the left sidebar of contact vertical

---

src/utils/normalize-mime-parts.ts

- Some mimes are having text/html part but it doesn't contain any data, in this case JS error was getting generated and because of that Modern UI was not able to display mail contents

ZBUG-3829 Fix error when showing mails which doesn't contain html content

---

src/schema/generated-schema-types.ts
src/schema/schema.graphql

- Added isOwner info in Contact type
PR for [zm-x-web](https://github.com/Zimbra/zm-x-web/pull/4907)

PREAPPS-7688: Show Distribution List attributes in reading pane of contact vertical when user select the DL from left sidenav

---

src/apollo/types.ts
src/apollo/zimbra-in-memory-cache.ts

We are using cached data for messages in message view. The related changes are in this PR - https://github.com/Zimbra/zm-x-web/pull/4970
Since the cached data is used it exposed couple of issues mainly because the emailAddress field cached from the GetMsg API call was getting overridden by the same field cached by the message search request. This is fixed by specifying how to cache email address field.

PREAPPS-7737: merge emailAddresses field in cache in order to use cached message response in modernUI

---

src/schema/generated-schema-types.ts
src/schema/schema.graphql

- Added unknown variable in SearchType enum. Required when we accept share of whole account that is shared with another user by cli command.

PREAPPS-7296: Add a friend's calendar option from Calendar vertical

---

src/schema/schema.graphql

…etadata to control the show/hide functionality of the mute conversation modal

PREAPPS-8008: Added the zimbraPrefHideMuteConvModal flag in Mailbox Metadata to control the show/hide functionality of the mute conversation modal

---

src/batch-client/index.ts
src/batch-client/types.ts
src/schema/generated-schema-types.ts
src/schema/schema.graphql

Previously, we implemented the ignoreSameSite option in authRequest to prevent authentication failures caused by the addition of the SameSite cookie flag in the backend, as outlined in https://synacor.atlassian.net/browse/ZBUG-2397
With the recent updates in Electron, we are now explicitly setting SameSite=None for cookies in our application. As a result, the ignoreSameSite option is no longer necessary and can be safely removed.

PREAPPS-8066 Remove ignoreSameSite in Auth Requests

---

src/schema/generated-schema-types.ts
src/schema/schema.graphql

Adding two attributes to AccountInfo.
Note:
`zimbraFeatureMailRecallEnabled` and `zimbraFeatureMailRecallTime` in `generated-schema-types.ts` have been updated during auto-generation process.

ZCS-16326: added attributes to AccountInfo

---

src/schema/generated-schema-types.ts
src/schema/schema.graphql

`zimbraIsExternalVirtualAccount` will be used to determine whether user is external user or not and show the external user the shared folders.

ZBUG-4013: fixed issue of shared folders not visible to external accounts
